//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Gatekeeper_Core.Keys {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Keys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Keys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMS_Gatekeeper_Core.Keys.Keys", typeof(Keys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RateLimiterOptions:CleanupIntervalSecond.
        /// </summary>
        public static string CleanupIntervalKey {
            get {
                return ResourceManager.GetString("CleanupIntervalKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RateLimiterOptions:InactivityTimeoutSecond.
        /// </summary>
        public static string InactivityTimeoutKey {
            get {
                return ResourceManager.GetString("InactivityTimeoutKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RateLimiterOptions:MaximumMessagePerAccountPerSecond.
        /// </summary>
        public static string MaxPerAccountKeys {
            get {
                return ResourceManager.GetString("MaxPerAccountKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RateLimiterOptions:MaximumMessagePerBuisnessNumberPerSecond.
        /// </summary>
        public static string MaxPerNumberKeys {
            get {
                return ResourceManager.GetString("MaxPerNumberKeys", resourceCulture);
            }
        }
    }
}
